# Combat Settings
combat:
  disable-shields: false # Disables the use of shields.
  disable-sweep-attacks: false # Disable sweeping attacks.
  remove-cooldown: false # Remove the cooldown from new versions.
  disable-offhand: false # Disables offhand use.
  critical-multiplier: 1.2 # 1.5 is 50% (default) and will add 50% damage when you crit.

# Pearl Settings
pearl:
  no-damage-ticks: 10 # The amount of no damage ticks after using an enderpearl.

# Regen Settings
regen:
  heal-rate: 3 # The rate of healing.

# Other Misc Settings
movement:
  disable-pushing-players: true # Disable players pushing other players.

# Knockback Settings (<3 hcfrevival)
kb:
  ground-check: false # Ensure player is on ground for sprint.
  values:
    horizontal: 0.35 # Changes the horizontal kb value.
    vertical: 0.35 # Changes the vertical kb value.
    extra-horizontal: 0.425 # Changes the extra horizontal kb value.
    extra-vertical: 0.085 # Changes the extra vertical kb value.
    vertical-limit: 0.4 # Changes the vertical limit kb value.
    sprint-reset-modifier: 1.0 # Changes the sprint reset modifier kb value.
    sprint-modifier: 0.5 # Changes the sprint modifier kb value.